In [1]:
%reload_ext autoreload
%autoreload 2

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
## Environment
# Change main system path to be able to run code from src folder
import sys
p = sys.path[0]
# Mac OS
if sys.path[0].endswith('/models'):
    main_path = p[:-len('/models')]
sys.path[0] = main_path

import os, gc
from termcolor import colored
import pandas as pd
from src import config

In [3]:
include_val_loss = False
include_sam = False

In [4]:

if include_val_loss:
    cvloss_files = [each for each in os.listdir(config.MODELS_DIR) if (each.endswith('_cvloss.csv') | 
                                                                    each.endswith('_Vloss.csv'))]
else:
    cvloss_files = [each for each in os.listdir(config.MODELS_DIR) if (each.endswith('_cvloss.csv'))]
    
print(len(cvloss_files))

23

In [5]:
model_summary = pd.DataFrame()
for i in cvloss_files:
    df = pd.read_csv(os.path.join(config.MODELS_DIR, i), index_col='target')
    model_summary = pd.concat([model_summary, df], axis=1)

target_labels_list = model_summary.index.tolist()

In [6]:
model_summary.style.highlight_min(axis=1,
                                  props='color:darkblue;\
                                         background-color:lightblue;')

In [7]:
model_sum = model_summary.T.copy()
model_sum['overall'] = model_sum.mean(axis=1)
if not include_sam:
    model_sum = model_sum[model_sum.index in [i for i in model_sum.index if not i.endswith('_sam')]]
model_sum.sort_values(by='overall')\
             .style.highlight_min(axis=0, 
                                  props='color:darkblue; background-color:lightblue;',
                                  subset=target_labels_list)\
                    .highlight_min(axis=0, 
                                   props='color:white; background-color:red;',
                                   subset=['overall'])

In [8]:
FTS_NAME = 'fts_mra_tempmz'
# Get all the models with the above feature(s)
MODELS = [i for i in model_sum.index if (i.startswith(FTS_NAME) & 
                                         (len(i) < (len(FTS_NAME)+14)))]
# Get the selected models from model_sum
model_sum[model_sum.index.isin(MODELS)].sort_values(by='overall')\
             .style.highlight_min(axis=0, 
                                  props='color:darkblue; background-color:lightblue;',
                                  subset=target_labels_list)\
                    .highlight_min(axis=0, 
                                   props='color:white; background-color:red;',
                                   subset=['overall'])

In [9]:
FTS_NAME = 'fts_mra_tempmz_cntpk_mratt'
# Get all the models with the above feature(s)
MODELS = [i for i in model_sum.index if (i.startswith(FTS_NAME) & 
                                         (len(i) < (len(FTS_NAME)+14)))]
# Get the selected models from model_sum
model_sum[model_sum.index.isin(MODELS)].sort_values(by='overall')\
             .style.highlight_min(axis=0, 
                                  props='color:darkblue; background-color:lightblue;',
                                  subset=target_labels_list)\
                    .highlight_min(axis=0, 
                                   props='color:white; background-color:red;',
                                   subset=['overall'])